### ISSUE TITLE
API HASH

### ISSUE THREAD

**Issue by mirage2812** [GravelFire/Tomarket#11]
Для каждого аккаунта нужно генерировать ID и HASH?

**Comment by SoloWay9** [comment]
> Для каждого аккаунта необходимо ограничить ID и HASH?

нет, копируешь один и используешь его для всех аккаунтов

**Comment by mirage2812** [comment]
подскажи как в один проект 100 акаунтов добавить? я так понимаю сейчас нужно просто копировать весь код и открывать в новом окне IDE?
