### ISSUE TITLE
Unclosed client session

### ISSUE THREAD

**Issue by mirage2812** [GravelFire/Tomarket#21]
При выключении main появляются ошибки для КАЖДОЙ сессии, пишет она не закрыта
![image](https://github.com/user-attachments/assets/4384357a-cac1-4eae-9caa-9755f26840c8)

**Comment by SP-l33t** [comment]
Это происходит именно потому, что ты закрываешь выполнение скрипта, не ожидая завершения сессий. Это так и должно быть.

**Comment by mirage2812** [comment]
Но в это время была пауза на всех акках, как то можно обработать их, чтобы они закрылись без ошибки?

**Comment by SP-l33t** [comment]
Обработать то можно. Но это 100% ни на что не влияет
